--<ScriptOptions statementTerminator=";"/>

ALTER TABLE ESTADISTICA_IDIOMA DROP CONSTRAINT FKESTADISTICA;

ALTER TABLE DEFIDIOMA DROP CONSTRAINT FK_IDIOMA;

ALTER TABLE DEFIDIOMA DROP CONSTRAINT FK_ESTADISTICA;

ALTER TABLE ESTADISTICA_IDIOMA DROP CONSTRAINT FKIDIOMA;

ALTER TABLE IDIOMA DROP CONSTRAINT IDIOMA_PK;

ALTER TABLE ESTADISTICA DROP CONSTRAINT ESTADISTICA_PK;

ALTER TABLE DEFIDIOMA DROP CONSTRAINT DEFIDIOMA_PK;

DROP TABLE IDIOMA;

DROP TABLE ESTADISTICA;

DROP TABLE ESTADISTICA_IDIOMA;

DROP TABLE DEFIDIOMA;

DROP DIRECTORY ORACLE_OCM_CONFIG_DIR;

DROP DIRECTORY DATA_PUMP_DIR;

DROP DIRECTORY ORACLECLRDIR;

DROP DIRECTORY XMLDIR;

CREATE TABLE IDIOMA (
		IDIDIOMA NUMBER(19 , 0) NOT NULL,
		NOMBRE VARCHAR2(20) NOT NULL,
		DESCRIPCION VARCHAR2(20)
	);

CREATE TABLE ESTADISTICA (
		IDESTADISTICA NUMBER(19 , 0) NOT NULL,
		NOMBRE VARCHAR2(20),
		DESCRIPCION VARCHAR2(20)
	);

CREATE TABLE ESTADISTICA_IDIOMA (
		IDESTADISTICA NUMBER(19 , 0) NOT NULL,
		IDIDIOMA NUMBER(19 , 0) NOT NULL
	);

CREATE TABLE DEFIDIOMA (
		IDESTADISTICA NUMBER(19 , 0) NOT NULL,
		IDIDIOMA NUMBER(19 , 0) NOT NULL
	);

ALTER TABLE IDIOMA ADD CONSTRAINT IDIOMA_PK PRIMARY KEY (IDIDIOMA);

ALTER TABLE ESTADISTICA ADD CONSTRAINT ESTADISTICA_PK PRIMARY KEY (IDESTADISTICA);

ALTER TABLE DEFIDIOMA ADD CONSTRAINT DEFIDIOMA_PK PRIMARY KEY (IDESTADISTICA);

ALTER TABLE ESTADISTICA_IDIOMA ADD CONSTRAINT FKESTADISTICA FOREIGN KEY (IDESTADISTICA)
	REFERENCES ESTADISTICA (IDESTADISTICA);

ALTER TABLE DEFIDIOMA ADD CONSTRAINT FK_IDIOMA FOREIGN KEY (IDIDIOMA)
	REFERENCES IDIOMA (IDIDIOMA)
	ON DELETE SET NULL;

ALTER TABLE DEFIDIOMA ADD CONSTRAINT FK_ESTADISTICA FOREIGN KEY (IDESTADISTICA)
	REFERENCES ESTADISTICA (IDESTADISTICA);

ALTER TABLE ESTADISTICA_IDIOMA ADD CONSTRAINT FKIDIOMA FOREIGN KEY (IDIDIOMA)
	REFERENCES IDIOMA (IDIDIOMA);

